"""CORRELATE — group anomalous signals into incidents.

Density clustering over a four-dimension similarity space, behind a hard
shared-context gate, with candidate pairs generated by blocking.

The three ideas, and why each is here:

**Similarity, not a time window.** Grouping whatever fired in the same five
minutes is how two unrelated incidents end up in one ticket. Similarity
combines time proximity with service identity, dependency topology, and log
template overlap, so co-occurrence alone carries only 30% of the weight.

**The shared-context gate.** Similarity alone never groups anything. Two
signals may only cluster if they *also* share something concrete: the same
service, a direct dependency edge, or a trace id. This is the primary defence
against the worst failure in this problem — a false merge, which hides a real
incident inside another's ticket. A false split merely costs a duplicate.
Those errors are not symmetric, so the gate is deliberately strict.

**Blocking.** Scoring every pair is O(n²). Instead, candidate pairs are
generated from blocks (same service, same trace, dependency neighbours within
the window); pairs sharing no block are never scored, because the gate would
reject them anyway. The distance matrix is built sparse, and DBSCAN treats
unstored pairs as infinitely far apart — so the saving is real, not cosmetic.
"""

from __future__ import annotations

import math
import re
from collections import defaultdict
from dataclasses import dataclass, field
from datetime import timedelta
from itertools import combinations

import networkx as nx
import numpy as np
from scipy.sparse import csr_matrix
from sklearn.cluster import DBSCAN
from sklearn.neighbors import sort_graph_by_row_values

from .signal import Signal

# --------------------------------------------------------------------------
# tunables
# --------------------------------------------------------------------------

W_TIME = 0.30
W_SERVICE = 0.25
W_DEPENDENCY = 0.25
W_TEMPLATE = 0.20

WINDOW_BASE_MIN = 5.0     # adaptive window floor
WINDOW_MAX_MIN = 15.0     # ...and ceiling
TIME_SCALE_MIN = 4.0      # exponential decay constant

EPS = 0.62                # DBSCAN radius in distance units (1 - similarity)
MIN_SAMPLES = 2

# Hop distance → closeness. Beyond three hops two services are effectively
# unrelated for incident purposes, whatever the graph says.
_HOP_CLOSENESS = {0: 1.0, 1: 0.75, 2: 0.45, 3: 0.15}


# --------------------------------------------------------------------------
# dependency graph
# --------------------------------------------------------------------------


class DependencyGraph:
    """Service topology, used for both correlation and causality.

    Directed, because "A calls B" is not the same claim as "B calls A" — the
    causal engine depends on that direction. Correlation asks only about
    distance, so it reads the undirected view.
    """

    def __init__(self, edges: set[tuple[str, str]] | None = None) -> None:
        self.graph = nx.DiGraph()
        for caller, callee in edges or set():
            self.graph.add_edge(caller, callee)
        self._undirected = self.graph.to_undirected()
        self._hops: dict[tuple[str, str], int | None] = {}

    def add_edges(self, edges: set[tuple[str, str]]) -> None:
        for caller, callee in edges:
            self.graph.add_edge(caller, callee)
        self._undirected = self.graph.to_undirected()
        self._hops.clear()

    def hops(self, a: str, b: str) -> int | None:
        """Undirected shortest path length, or None if unreachable."""
        if a == b:
            return 0
        key = (a, b) if a <= b else (b, a)
        if key in self._hops:
            return self._hops[key]
        try:
            distance = nx.shortest_path_length(self._undirected, a, b)
        except (nx.NetworkXNoPath, nx.NodeNotFound):
            distance = None
        self._hops[key] = distance
        return distance

    def closeness(self, a: str, b: str) -> float:
        hop = self.hops(a, b)
        if hop is None:
            return 0.0
        return _HOP_CLOSENESS.get(hop, 0.0)

    def has_direct_edge(self, a: str, b: str) -> bool:
        return self.graph.has_edge(a, b) or self.graph.has_edge(b, a)

    def neighbours(self, service: str) -> set[str]:
        if service not in self._undirected:
            return set()
        return set(self._undirected.neighbors(service))

    def downstream_of(self, service: str) -> set[str]:
        """Everything reachable *following* call direction — the blast radius."""
        if service not in self.graph:
            return set()
        return set(nx.descendants(self.graph, service))

    def upstream_of(self, service: str) -> set[str]:
        if service not in self.graph:
            return set()
        return set(nx.ancestors(self.graph, service))


# --------------------------------------------------------------------------
# similarity
# --------------------------------------------------------------------------


def _minutes_apart(a: Signal, b: Signal) -> float:
    return abs((a.timestamp - b.timestamp).total_seconds()) / 60.0


def time_proximity(a: Signal, b: Signal) -> float:
    """Exponential decay, hard-zero past the adaptive ceiling."""
    dt = _minutes_apart(a, b)
    if dt > WINDOW_MAX_MIN:
        return 0.0
    return math.exp(-dt / TIME_SCALE_MIN)


def service_affinity(a: Signal, b: Signal) -> float:
    if a.service == b.service:
        return 1.0 if (a.component or "") == (b.component or "") else 0.85
    return 0.0


def template_similarity(a: Signal, b: Signal) -> float:
    """Same mined template is a strong match; otherwise token overlap.

    Token Jaccard is the fallback that carries correlation across sources —
    a Grafana alert and an application log describing the same failure share
    vocabulary even though neither has a template id.
    """
    if a.template_id and b.template_id and a.template_id == b.template_id:
        return 1.0
    tokens_a = _tokens(a)
    tokens_b = _tokens(b)
    if not tokens_a or not tokens_b:
        return 0.0
    overlap = len(tokens_a & tokens_b)
    return overlap / len(tokens_a | tokens_b)


_STOP = {"the", "a", "an", "in", "on", "of", "to", "for", "is", "was", "and", "at", "by"}

# Alarm notifications are mostly boilerplate: every CloudWatch alarm ever
# raised says "Threshold Crossed: 1 datapoint ... was greater than the
# threshold". Left in, two completely unrelated alarms score as near-identical
# text purely on that shared frame, which is precisely the wrong answer. The
# discriminating content of a metric alarm is its metric name, not its prose.
_BOILERPLATE = {
    "threshold", "crossed", "datapoint", "datapoints", "greater", "less",
    "than", "alarm", "state", "value", "values", "error", "errors", "failed",
    "failure", "exceeded", "exceeds",
}


_CAMEL_BOUNDARY = re.compile(r"(?<=[a-z0-9])(?=[A-Z])|(?<=[A-Z])(?=[A-Z][a-z])")
_WORD = re.compile(r"[a-z][a-z0-9]{2,}")


def _tokens(signal: Signal) -> set[str]:
    """Comparable vocabulary for a signal.

    Metric names are camelCase identifiers, not prose: left whole,
    `DatabaseConnections` shares no token with the log line "connection pool
    exhausted" that describes the very same failure — so the strongest piece
    of evidence linking a symptom to its cause scores exactly zero. Splitting
    on case boundaries and normalising trivial plurals restores that link,
    which is what lets a log burst be attributed to the right metric alarm
    when a service depends on several failing things at once.
    """
    raw = f"{signal.message} {signal.metric or ''} {signal.component or ''}"
    spaced = _CAMEL_BOUNDARY.sub(" ", raw).lower()
    found = _WORD.findall(spaced)

    tokens: set[str] = set()
    for token in found:
        if token in _STOP or token in _BOILERPLATE:
            continue
        # Fold simple plurals so "connections" matches "connection". Not a
        # real stemmer - just enough to stop trivial morphology from hiding
        # an obvious match, without the false merges aggressive stemming
        # would cause.
        if len(token) > 4 and token.endswith("s") and not token.endswith("ss"):
            token = token[:-1]
        if token not in _STOP and token not in _BOILERPLATE:
            tokens.add(token)
    return tokens


@dataclass
class SimilarityBreakdown:
    """Kept per accepted pair so a cluster can explain how it was formed."""

    time: float
    service: float
    dependency: float
    template: float
    total: float
    gate_reason: str


def similarity(
    a: Signal, b: Signal, graph: DependencyGraph
) -> SimilarityBreakdown | None:
    """Score a pair, or return None if the shared-context gate rejects it."""
    gate = _gate_reason(a, b, graph)
    if gate is None:
        return None

    t = time_proximity(a, b)
    if t == 0.0:
        return None  # outside the window entirely

    s = service_affinity(a, b)
    d = graph.closeness(a.service, b.service)
    tpl = template_similarity(a, b)
    total = W_TIME * t + W_SERVICE * s + W_DEPENDENCY * d + W_TEMPLATE * tpl
    return SimilarityBreakdown(t, s, d, tpl, total, gate)


def _gate_reason(a: Signal, b: Signal, graph: DependencyGraph) -> str | None:
    """The hard gate. Returns why the pair is admissible, or None.

    Order matters only for the explanation string — a shared trace id is the
    strongest evidence available (it is literally the same request), so it is
    reported in preference to weaker justifications.
    """
    if a.trace_id and b.trace_id and a.trace_id == b.trace_id:
        return "shared trace_id"
    if a.service == b.service:
        return "same service"
    if graph.has_direct_edge(a.service, b.service):
        return "direct dependency edge"
    if a.parent_service == b.service or b.parent_service == a.service:
        return "observed caller/callee in trace"
    return None


# --------------------------------------------------------------------------
# blocking
# --------------------------------------------------------------------------


def candidate_pairs(
    signals: list[Signal], graph: DependencyGraph
) -> tuple[set[tuple[int, int]], dict[str, int]]:
    """Generate index pairs worth scoring, via blocking.

    Three block families, matching the three ways the gate can be satisfied.
    Any pair not landing in a shared block would fail the gate anyway, so
    skipping it costs no recall — this is a pure cost optimisation, not an
    accuracy trade.
    """
    by_service: dict[str, list[int]] = defaultdict(list)
    by_trace: dict[str, list[int]] = defaultdict(list)
    for i, signal in enumerate(signals):
        by_service[signal.service].append(i)
        if signal.trace_id:
            by_trace[signal.trace_id].append(i)

    pairs: set[tuple[int, int]] = set()

    for members in by_service.values():
        pairs.update(combinations(sorted(members), 2))
    for members in by_trace.values():
        pairs.update(combinations(sorted(members), 2))

    # Dependency-neighbour block, restricted by time so a service pair that is
    # adjacent in the graph but hours apart never becomes a candidate.
    window = timedelta(minutes=WINDOW_MAX_MIN)
    services = sorted(by_service)
    for idx, svc_a in enumerate(services):
        neighbours = graph.neighbours(svc_a)
        for svc_b in services[idx + 1:]:
            if svc_b not in neighbours:
                continue
            for i in by_service[svc_a]:
                for j in by_service[svc_b]:
                    if abs(signals[i].timestamp - signals[j].timestamp) <= window:
                        pairs.add((i, j) if i < j else (j, i))

    n = len(signals)
    stats = {
        "possible_pairs": n * (n - 1) // 2,
        "candidate_pairs": len(pairs),
    }
    return pairs, stats


# --------------------------------------------------------------------------
# clustering
# --------------------------------------------------------------------------


@dataclass
class Cluster:
    cluster_id: int
    signals: list[Signal]
    gate_reasons: dict[str, int] = field(default_factory=dict)
    mean_similarity: float = 0.0
    confidence: float = 0.0

    @property
    def services(self) -> list[str]:
        return sorted({s.service for s in self.signals})

    @property
    def start(self):
        return min(s.timestamp for s in self.signals)

    @property
    def end(self):
        return max(s.timestamp for s in self.signals)


@dataclass
class CorrelationReport:
    input_signals: int = 0
    clustered: int = 0
    noise: int = 0
    clusters_formed: int = 0
    possible_pairs: int = 0
    candidate_pairs: int = 0
    scored_pairs: int = 0
    gate_rejected: int = 0


def correlate(
    signals: list[Signal], graph: DependencyGraph
) -> tuple[list[Cluster], list[Signal], CorrelationReport]:
    """Cluster anomalous signals into incidents.

    Only anomalous signals are considered — correlating everything would mean
    clustering healthy traffic, and the whole point of DETECT is to shrink
    what CORRELATE has to reason about.
    """
    anomalous = [s for s in signals if s.is_anomaly]
    report = CorrelationReport(input_signals=len(anomalous))

    if len(anomalous) < 2:
        report.noise = len(anomalous)
        return [], anomalous, report

    pairs, stats = candidate_pairs(anomalous, graph)
    report.possible_pairs = stats["possible_pairs"]
    report.candidate_pairs = stats["candidate_pairs"]

    rows: list[int] = []
    cols: list[int] = []
    data: list[float] = []
    breakdowns: dict[tuple[int, int], SimilarityBreakdown] = {}

    for i, j in pairs:
        result = similarity(anomalous[i], anomalous[j], graph)
        if result is None:
            report.gate_rejected += 1
            continue
        distance = 1.0 - result.total
        if distance > EPS:
            continue
        breakdowns[(i, j)] = result
        # Symmetric entries: DBSCAN reads the matrix in both directions.
        rows.extend([i, j])
        cols.extend([j, i])
        # A stored zero would be dropped by the sparse format and read back as
        # "not a neighbour" — the exact opposite of distance zero. Floor it.
        data.extend([max(distance, 1e-6)] * 2)

    report.scored_pairs = len(breakdowns)

    n = len(anomalous)
    matrix = csr_matrix((data, (rows, cols)), shape=(n, n))
    # sklearn scans each row assuming ascending distances; handing it an
    # unsorted graph works but re-sorts internally and warns every call.
    matrix = sort_graph_by_row_values(matrix, warn_when_not_sorted=False)
    labels = DBSCAN(eps=EPS, min_samples=MIN_SAMPLES, metric="precomputed").fit_predict(matrix)

    grouped: dict[int, list[int]] = defaultdict(list)
    for idx, label in enumerate(labels):
        grouped[int(label)].append(idx)

    noise = [anomalous[i] for i in grouped.pop(-1, [])]
    clusters: list[Cluster] = []
    for new_id, (_, members) in enumerate(sorted(grouped.items())):
        cluster = Cluster(
            cluster_id=new_id,
            signals=sorted((anomalous[i] for i in members), key=lambda s: s.timestamp),
        )
        _annotate(cluster, members, breakdowns)
        clusters.append(cluster)

    report.clusters_formed = len(clusters)
    report.clustered = sum(len(c.signals) for c in clusters)
    report.noise = len(noise)
    return clusters, noise, report


def near_misses(
    cluster: Cluster, noise: list[Signal], graph: DependencyGraph, limit: int = 4
) -> list[tuple[Signal, str]]:
    """Signals that fired near this incident but were deliberately excluded.

    Surfacing these is what lets a reviewer trust the grouping. "17 signals
    became 1 incident" is a claim; "and here is the disk-usage warning that
    fired inside the same window, excluded because it shares no service,
    dependency edge or trace" is evidence. It also makes a *wrong* exclusion
    catchable in seconds rather than during the next outage.
    """
    window = timedelta(minutes=WINDOW_MAX_MIN)
    out: list[tuple[Signal, str]] = []

    for signal in noise:
        if signal.timestamp < cluster.start - window or signal.timestamp > cluster.end + window:
            continue
        reason = _exclusion_reason(signal, cluster, graph)
        if reason:
            out.append((signal, reason))
        if len(out) >= limit:
            break
    return out


def _exclusion_reason(signal: Signal, cluster: Cluster, graph: DependencyGraph) -> str:
    """Name the specific gate condition this signal failed."""
    services = set(cluster.services)
    traces = {s.trace_id for s in cluster.signals if s.trace_id}

    if signal.service in services:
        return ""  # same service — it was excluded on similarity, not the gate
    if signal.trace_id and signal.trace_id in traces:
        return ""
    if any(graph.has_direct_edge(signal.service, svc) for svc in services):
        return "adjacent in the dependency graph but below the similarity threshold"
    return "no shared service, dependency edge, or trace id"


def _annotate(
    cluster: Cluster,
    members: list[int],
    breakdowns: dict[tuple[int, int], SimilarityBreakdown],
) -> None:
    """Record how a cluster was held together, and how much to trust it.

    Confidence is driven by the *weakest* kind of evidence used, not the
    average: a cluster joined mostly by shared trace ids but with one member
    attached by loose token overlap deserves a reviewer's attention on exactly
    that member. Reporting a comfortable mean would hide it.
    """
    inside = set(members)
    reasons: dict[str, int] = {}
    scores: list[float] = []
    for (i, j), breakdown in breakdowns.items():
        if i in inside and j in inside:
            reasons[breakdown.gate_reason] = reasons.get(breakdown.gate_reason, 0) + 1
            scores.append(breakdown.total)

    cluster.gate_reasons = dict(sorted(reasons.items(), key=lambda kv: -kv[1]))
    cluster.mean_similarity = float(np.mean(scores)) if scores else 0.0

    strong = reasons.get("shared trace_id", 0) + reasons.get("same service", 0)
    total = sum(reasons.values()) or 1
    strong_share = strong / total
    cluster.confidence = round(
        min(0.35 + 0.45 * strong_share + 0.30 * cluster.mean_similarity, 1.0), 2
    )
